version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production:
        dependency-type: production
        update-types:
          - patch
    schedule:
      interval: daily
      time: "04:20"
      timezone: "Africa/Douala"
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      actions-minor:
        update-types:
          - minor
          - patch
    schedule:
      interval: weekly
      day: "monday"
      time: "04:50"
      timezone: "Africa/Douala"
