ARG NODE_VERSION=21.7.1

FROM node:${NODE_VERSION}-alpine

WORKDIR /usr/src/ts_devcontainer

COPY package*.json .

# Install dependecies and cache them.
RUN --mount=type=cache,target=/root/.npm \
    npm install

COPY . .

ENTRYPOINT [ "npm", "run", "start:dev" ]

EXPOSE 3000:3000