services:
  app:
    build: 
      context: ..
      dockerfile: Dockerfile.dev
    volumes:
      - /workspaces/tenantsphere:/usr/src/app:cached
    env_file: ./.env
    depends_on:
      - db
    ports:
      - 3005:3000
    environment:
      - DB_HOST=db
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
     MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
     MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
     MONGO_INITDB_DATABASE: $MONGODB_DATABASE

volumes:
  mongodb-data: