name: Versioning

on:
  workflow_call:
    inputs:
      token:
        description: The github token
        required: true
        type: string

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump_version.outputs.new_version }}
    steps:
      - name: Bump version
        id: bump_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ inputs.token }}
          release_branches: main
          dry_run: true
